In [1]:
import numpy as np

In [8]:
np.random.seed(0)

In [9]:
x1 = np.random.randint(10, size=6)

In [10]:
x1

array([5, 0, 3, 3, 7, 9])

In [11]:
x2 = np.random.randint(10, size=(3,4))

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
x3 = np.random.randint(10, size=(3,4,2))

In [14]:
x3

array([[[8, 1],
        [5, 9],
        [8, 9],
        [4, 3]],

       [[0, 3],
        [5, 0],
        [2, 3],
        [8, 1]],

       [[3, 3],
        [3, 7],
        [0, 1],
        [9, 9]]])