In [2]:
print("Day2")
import numpy as np

Day2


In [3]:
a = np.array([1,2,3,4,5])
a = np.insert(a, 2, 100)
print(a)

[  1   2 100   3   4   5]


In [4]:
arr =np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    print(x)

[1 2 3 4]
[5 6 7 8]


In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [6]:
arr3 = np.array(['apple','cherry','banana','dragon-fruit'])

x = np.sort(arr3)
print(x)

['apple' 'banana' 'cherry' 'dragon-fruit']


In [8]:
from numpy import random

y1 = random.normal(loc=1, scale=2, size=(2, 3))
y2 = random.binomial(n=10, p=0.5, size=10)
y3 = random.poisson(lam=2, size=10)
y4 = random.uniform(size=(2, 3))
y5 = random.logistic(loc=1, scale=2, size=(2, 3))

print(y1)
print("-------")
print(y2)
print("-------")
print(y3)
print("-------")
print(y4)
print("-------")
print(y5)

[[-3.698363    2.30225611 -0.181661  ]
 [ 0.13050879  1.11926628  2.57199537]]
-------
[7 9 5 9 5 3 5 4 5 8]
-------
[2 0 4 1 5 1 6 3 1 0]
-------
[[0.01752293 0.47208056 0.58660191]
 [0.59971715 0.54385499 0.67596736]]
-------
[[ 3.52808501 -0.14007722  5.90163731]
 [ 2.99734251  0.77366986  3.75476495]]
