In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [4]:
print(arr)

[[1 2]
 [3 4]]


In [5]:
np.__version__

'1.24.1'

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
## we can even us tupple to create anarray

In [11]:
arr1 = np.array(42)
arr1

array(42)

In [12]:
print(arr1)

42


In [10]:
# we will now create 3-d array

In [16]:
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [17]:
print(arr2)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [18]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [20]:
print(arr,arr.ndim)


42 0


In [22]:
print(arr1,arr1.ndim)

42 0


In [23]:
print(arr2,arr2.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 3


In [24]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [25]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [26]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [27]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2
