In [1]:
def square(x):
    """square a number"""
    return x ** 2

for N in range(1, 4):
    print(f"{N} squared is {square(N)}")
    

1 squared is 1
2 squared is 4
3 squared is 9


In [2]:
square(5)

25

In [3]:
import math

In [4]:
math.sin(2)

0.9092974268256817

In [5]:
math.cos(4)

-0.6536436208636119

In [6]:
math.tan(2)

-2.185039863261519

In [7]:
import numpy

In [8]:
numpy.__version__

'1.24.1'

In [9]:
import numpy as np

In [10]:
x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
x
# array([[  0,   1,   2,   3,   4],
#        [-99,   6, -99,   8, -99],
#        [-99,  11, -99,  13, -99]])

x.max(axis=1)
# array([ 4,  8, 13])

# Generate normally distributed random numbers:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples

array([-0.42819619,  0.58488284, -0.98329435, ...,  2.50795549,
       -0.75111679, -1.42982249])